micronaut:
  application:
    name: micronautci
mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/mydb
consul:
  client:
    registration:
      enabled: true
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
netty:
  default:
    allocator:
      max-order: 3
db:
  name: 'fruit'
  collection: 'fruit'
