name: Java CI with Gradle

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]
  release:
    types: [ published ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: cantte/fruits

jobs:
  avoid_redundancy:

    runs-on: ubuntu-latest

    steps:
      - name: cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  publish:

    if: github.event_name == 'release'

    needs: [ build ]

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: install consign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.4.0'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: build docker image with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dockerBuildNative

      - name: push docker image with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: dockerPushNative